
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST= postgres
      - DB_USER= ${DB_USER}
      - DB_PASSWORD= ${DB_PASSWORD}
      - DB_NAME= ${DB_NAME}
      - DB_SSL_MODE= ${DB_SSL_MODE}
      - JWT_SECRET= ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - otp-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otp-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U amir -d user-auth" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  otp-network:
    driver: bridge